---
title: "Flex Dashboards HTML Widgets"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

``` {r librerias}
library(flexdashboard)
library(readr)
library(dplyr)
library(leaflet)
library(DT)
library(crosstalk)
```

```{r dataset}
earthquakedata <- read.csv("earthquakedata.csv")
```

# Leaflet
##
###

```{r}
earthquakedata %>%
  filter(yr==1995) %>%
  DT::datatable()
```

###

```{r}
earthquakedata %>%
  filter(yr==1995) %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon,
             lat=~lat,
             label=~mag)
```

# crosstalk
```{r}
data_shared <- SharedData$new(earthquakedata %>%
                                filter(yr==2000))
```

##

### tabla
```{r}
filter_slider("mag","Magnitud",data_shared,step=0.1,width=250,column=~mag)
filter_select("yr","Year",data_shared,group=~yr,multiple=FALSE)
```

###
```{r}
data_shared %>%
  DT::datatable()
```

###

```{r}
data_shared %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon,
             lat=~lat,
             label=~yr)
```



